name: notepases
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # ===============================
  # State Management & DI
  # ===============================
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  get_it: ^8.2.0
  injectable: ^2.5.1

  # ===============================
  # UI & Icons
  # ===============================
  font_awesome_flutter: ^10.12.0

  # ===============================
  # Maps & Location
  # ===============================
  google_maps_flutter: ^2.13.1
  geolocator: ^14.0.2
  google_places_flutter: ^2.1.0
  geocoding: ^4.0.0
  flutter_polyline_points: ^3.1.0

  # ===============================
  # Firebase Core
  # ===============================
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_messaging: ^15.0.0

  # ===============================
  # Auth Providers
  # ===============================
  google_sign_in: ^6.0.0
  flutter_facebook_auth: ^7.0.0
  sign_in_with_apple: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Code generation (Injectable)
  injectable_generator: ^2.8.1
  build_runner: ^2.7.1

flutter:
  uses-material-design: true

  # ===============================
  # Assets
  # ===============================
  assets:
    - assets/images/

  # ===============================
  # Fonts
  # ===============================
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/static/Inter-Regular.ttf

    - family: OpenSans
      fonts:
        - asset: assets/fonts/Open_Sans/static/OpenSans/OpenSans-Regular.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
          weight: 700
